-- explorer
vim.keymap.set("n", "<leader>e", function()
  vscode.action("workbench.explorer.fileView.focus")
end)
vim.keymap.set("n", "<leader>fe", function()
  vscode.action("workbench.explorer.fileView.focus")
end)
--
vim.keymap.set({ "n", "x" }, "<leader>;", function()
  vscode.action("workbench.action.showCommands")
end)
vim.keymap.set("n", "<leader>,", function()
  vscode.action("workbench.action.showAllEditors")
end)
vim.keymap.set({ "n", "x" }, "<leader>/", function()
  vscode.action("workbench.action.quickTextSearch")
end)
vim.keymap.set({ "n", "x" }, "<leader>?", function()
  vscode.action("workbench.action.findInFiles")
end)
vim.keymap.set("n", "<leader><space>", function()
  vscode.action("workbench.action.quickOpen")
end)
-- find
vim.keymap.set("n", "<leader>fb", function()
  vscode.action("workbench.action.showAllEditors")
end)
vim.keymap.set("n", "<leader>fc", function()
  vscode.action("workbench.action.openSettingsJson")
end)
vim.keymap.set("n", "<leader>fC", function()
  vscode.action("workbench.action.openWorkspaceSettingsFile")
end)
vim.keymap.set("n", "<leader>ff", function()
  vscode.action("workbench.action.quickOpen")
end)
vim.keymap.set("n", "<leader>fg", function()
  vscode.action("workbench.scm.focus")
end)
vim.keymap.set("n", "<leader>fk", function()
  vscode.action("workbench.action.openGlobalKeybindingsFile")
end)
vim.keymap.set("n", "<leader>fr", function()
  vscode.action("workbench.action.openRecent")
end)
-- vim.keymap.set("n", "<leader>fR", function()
--   vscode.action("workbench.action.openRecent", { args = { "files" } })
-- end)
vim.keymap.set("n", "<leader>fn", function()
  vscode.action("workbench.action.files.newUntitledFile")
end)
vim.keymap.set("n", "<leader>ft", function()
  vscode.action("workbench.action.quickOpenTerm")
end)
vim.keymap.set("n", "<C-/>", function()
  vscode.action("workbench.action.terminal.toggleTerminal")
end)
