vim.keymap.set("n", "gK", function()
  vscode.action("editor.action.triggerParameterHints")
end)
vim.keymap.set("n", "gI", function()
  vscode.action("editor.action.goToImplementation")
end)
vim.keymap.set("n", "gy", function()
  vscode.action("editor.action.goToTypeDefinition")
end)
vim.keymap.set("n", "gY", function()
  vscode.action("editor.action.peekTypeDefinition")
end)

vim.keymap.set("n", "<leader>ss", function()
  vscode.action("workbench.action.gotoSymbol")
end)
vim.keymap.set("n", "<leader>sS", function()
  vscode.action("workbench.action.showAllSymbols")
end)

vim.keymap.set("n", "<leader>xx", function()
  vscode.action("workbench.action.problems.focus")
end)

vim.keymap.set({ "n", "x" }, "]d", function()
  vscode.action("editor.action.marker.next")
end)
vim.keymap.set({ "n", "x" }, "[d", function()
  vscode.action("editor.action.marker.prev")
end)

vim.keymap.set("n", "<leader>ca", function()
  vscode.action("editor.action.quickFix")
end)
vim.keymap.set("n", "<leader>cA", function()
  vscode.action("editor.action.sourceAction")
end)
vim.keymap.set("n", "<leader>cc", function()
  vscode.action("codelens.showLensesInCurrentLine")
end)
vim.keymap.set("n", "<leader>cd", function()
  vscode.action("errorLens.searchForProblem")
end)
vim.keymap.set("n", "<leader>cf", function()
  vscode.action("editor.action.formatDocument")
end)
vim.keymap.set("n", "<leader>cr", function()
  vscode.action("editor.action.rename")
end)
vim.keymap.set("n", "<leader>cR", function()
  vscode.action("file-browser.rename")
end)
vim.keymap.set("n", "<leader>cs", function()
  vscode.action("outline.focus")
end)
