-- grep
vim.keymap.set("n", "<leader>sb", function()
  vscode.action("search.action.openEditor")
end)
-- search

vim.keymap.set("n", "<leader>sd", function()
  vscode.action("workbench.action.problems.focus")
end)
vim.keymap.set("n", "<leader>sk", function()
  vscode.action("workbench.action.openGlobalKeybindings")
end)
vim.keymap.set("n", "<leader>sp", function()
  vscode.action("workbench.extensions.action.focusExtensionsView")
end)
vim.keymap.set("n", "<leader>sr", function()
  vscode.action("workbench.action.findInFiles")
end)
vim.keymap.set("n", "<leader>sv", function()
  vscode.action("workbench.action.openView")
end)
vim.keymap.set("n", "<leader>s'", function()
  vim.cmd("map")
  vscode.action("workbench.panel.output.focus")
  vim.defer_fn(function()
    vscode.action("actions.find")
  end, 200)
end)
