vim.keymap.set("n", "<leader>j", function()
  vscode.action("bookmarks.toggle")
end)
vim.keymap.set("n", "<leader>J", function()
  vscode.action("bookmarks.toggleLabeled")
end)
vim.keymap.set({ "n", "x" }, "]j", function()
  vscode.action("bookmarks.jumpToNext")
end)
vim.keymap.set({ "n", "x" }, "[j", function()
  vscode.action("bookmarks.jumpToPrevious")
end)
vim.keymap.set("n", "<leader>sj", function()
  vscode.action("bookmarks.list")
end)
vim.keymap.set("n", "<leader>sJ", function()
  vscode.action("bookmarks.listFromAllFiles")
end)
